/*
* Copyright 2012 Tomasz Kamiński
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package org.spiderland.Psh;

import java.util.ArrayList;

/**
 * Semantic interpreter
 */
public class SemanticInterpreter extends Interpreter {

	/**
	 * Generates list of all possible programs with given size
	 * @param size size of the programs
	 * @return
	 */
	public ArrayList<Program> generateAllPrograms(int size) {
		return generateAllPrograms(size, false);
	}
	
	/**
	 * Generates list of all possible programs with given size. Resulting set
	 * may consist numbers generated by ERC's
	 * new MersenneTwisterFast()
	 * @param size
	 * @param containNumbers
	 * @return
	 */
	public ArrayList<Program> generateAllPrograms(int size, boolean containNumbers) {
		ArrayList<Program> set = new ArrayList<Program>();
		
		if (size > 0)
			generateAllPrograms(set, new Program(), size, containNumbers);
		
		return set;
	}
	
	private void generateAllPrograms(ArrayList<Program> set, Program program, int size, boolean containNumbers) {
		if (size == 0) {
			set.add((Program) program.clone());
		} else {
			for (AtomGenerator generator : _randomGenerators)
				if (containNumbers
						|| (generator instanceof InstructionAtomGenerator)) {
					program.push(generator.Generate(this));
					generateAllPrograms(set, program, size-1, containNumbers);
					program.pop();
				}
		}
	}
	
	public InterpreterState getMemoryState() {
		InterpreterState state = new InterpreterState(this);
		return state;
	}
	
	public void setMemoryState(InterpreterState state) {
		_floatStack = state.getFloatStack();
		_intStack = state.getIntStack();
		_boolStack = state.getBoolStack();
		_inputStack = state.getInputStack();
		_nameStack = state.getNameStack();
		_codeStack = state.getCodeStack();
		UpdateStackInstructions();
	}
	
	public ArrayList<AtomGenerator> getRandomGenerators() {
		return this._randomGenerators;
	}
}
